"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
electron_1.contextBridge.exposeInMainWorld('electronAPI', {
    onScreenshotRequest: (callback) => electron_1.ipcRenderer.on('screenshot-request', callback),
    offScreenshotRequest: () => electron_1.ipcRenderer.removeAllListeners('screenshot-request'),
    onProcessScreenshot: (callback) => electron_1.ipcRenderer.on('process-screenshot', (_event, imageData) => callback(imageData)),
    requestScreenshot: () => electron_1.ipcRenderer.invoke('request-screenshot'),
    captureScreenshot: (x, y, width, height) => electron_1.ipcRenderer.invoke('capture-screenshot', x, y, width, height),
    captureScreen: () => electron_1.ipcRenderer.invoke('capture-screen'),
    minimizeCurrentWindow: () => electron_1.ipcRenderer.invoke('minimize-current-window'),
    openScreenshotOverlay: () => electron_1.ipcRenderer.invoke('open-screenshot-overlay'),
    closeScreenshotOverlay: (options) => electron_1.ipcRenderer.invoke('close-screenshot-overlay', options),
    getScreenshotOverlayStatus: () => electron_1.ipcRenderer.invoke('get-screenshot-overlay-status'),
    onScreenshotOverlayStatus: (callback) => electron_1.ipcRenderer.on('screenshot-overlay-status', (_event, status) => callback(status)),
    offScreenshotOverlayStatus: () => electron_1.ipcRenderer.removeAllListeners('screenshot-overlay-status'),
    onScreenshotCaptured: (callback) => electron_1.ipcRenderer.on('screenshot-captured', (_event, imageData) => callback(imageData)),
    offScreenshotCaptured: () => electron_1.ipcRenderer.removeAllListeners('screenshot-captured'),
    getOverlayScreenshot: () => electron_1.ipcRenderer.invoke('get-overlay-screenshot'),
    onTranslationComplete: (callback) => electron_1.ipcRenderer.on('translation-complete', (_event, imageData, translatedText) => callback(imageData, translatedText)),
    offTranslationComplete: () => electron_1.ipcRenderer.removeAllListeners('translation-complete'),
    onOpenRecentResult: (callback) => electron_1.ipcRenderer.on('open-recent-result', () => callback()),
    offOpenRecentResult: () => electron_1.ipcRenderer.removeAllListeners('open-recent-result'),
    sendTranslationResult: (imageData, translatedText) => electron_1.ipcRenderer.send('translation-complete', imageData, translatedText),
    performOCR: (imageData) => electron_1.ipcRenderer.invoke('perform-ocr', imageData),
    updateShortcut: (shortcutKey) => electron_1.ipcRenderer.send('update-shortcut', shortcutKey),
    getShortcutStatus: () => electron_1.ipcRenderer.invoke('get-shortcut-status'),
    onShortcutStatus: (callback) => electron_1.ipcRenderer.on('shortcut-status', (_event, status) => callback(status)),
    offShortcutStatus: () => electron_1.ipcRenderer.removeAllListeners('shortcut-status'),
    createPinWindow: (imageData, ocrText, translatedText) => electron_1.ipcRenderer.invoke('create-pin-window', imageData, ocrText, translatedText),
    setAlwaysOnTop: (windowId, alwaysOnTop) => electron_1.ipcRenderer.invoke('set-always-on-top', windowId, alwaysOnTop),
    closePinWindow: (windowId) => electron_1.ipcRenderer.invoke('close-pin-window', windowId),
    closeCurrentWindow: () => electron_1.ipcRenderer.invoke('close-current-window'),
    moveCurrentWindow: (x, y) => electron_1.ipcRenderer.invoke('move-current-window', x, y),
    resizeCurrentWindow: (width, height) => electron_1.ipcRenderer.invoke('resize-current-window', width, height),
    onPinWindowData: (callback) => electron_1.ipcRenderer.on('pin-window-data', (_event, data) => callback(data)),
    offPinWindowData: () => electron_1.ipcRenderer.removeAllListeners('pin-window-data'),
});
//# sourceMappingURL=preload.js.map